### ISSUE TITLE
Can't find settings menu on iOS

### ISSUE THREAD

**Issue by Maicoletf** [WamWooWam/RSDKv5-Decompilation#2]
Hello, I just wanted to ask for information about the sonic mania DLC since I am a cell phone user (ios) and I cannot activate the plus, I don't know if it is externally or internally that I have to activate it

**Comment by Skeio200git** [comment]
Go to settings and then scroll all the way down and you should see an app called "rsdkv5" click on it and you should see a toggle that says "enable plus dlc" switch it on and it should work

**Comment by juins1** [comment]
this works with trollstore installed apps when you change from system to user. But this game specifically does not show the settings even when you change system to user. It is the first instance I've seen of this. The only way i got it to show was by installing it thru appsync (on ios14). But on my ios15 phone i cant get settings to show, and appsync does not work for ios15 atm.

 It would be nice if an update for this issue was pushed

**Comment by WamWooWam** [comment]
> But this game specifically does not show the settings even when you change system to user. 

Lil late getting back to this my apologies, the app not showing up in iOS' Settings is entirely outside of my control unfortunately, it's down to the OS and how exactly the app gets sideloaded. Sorry about this!

**Comment by HyperLemons** [comment]
> > But this game specifically does not show the settings even when you change system to user. 
> 
> 
> 
> Lil late getting back to this my apologies, the app not showing up in iOS' Settings is entirely outside of my control unfortunately, it's down to the OS and how exactly the app gets sideloaded. Sorry about this!

What are the known ways to sideload that allows the Settings options besides Appsync?

**Comment by WamWooWam** [comment]
Anything that sideloads as a developer app or non-system app should work
